### ISSUE TITLE
Writing profiling output to STDOUT

### ISSUE THREAD

**Issue by camilo1729** [cea-hpc/selFIe#1]
Hello,

Is it possible to print out the result of the profiling on STDOUT ? I tried using  SELFIE_PRINT_=1 but it shows just a summary:

=== SELFIE DETAILS ===

   - Execution time : 74.247798
   - Command : /home/cr3db69n/benchmarks/nas/NPB3.3.1/NPB3.3-MPI/bin/lu.C.8
   - Environment variables -

                   USER : cristian

I'm a normal user in the cluster and I cannot read the syslog file.

Thank you in advance.

**Comment by laurent-nguyen** [comment]
Hello Cristian,

what do you need to be printed on the STDOUT ? (the JSON or the detailed profiling ?)

Among the next features, I'll add printing result to a file.

**Comment by camilo1729** [comment]
Hello,  I need to print out the generated JSON, I would like a line line like:

selfie[26058]: { "utime": 0.00, "stime": 0.01, "maxmem": 0.00, "posixio_time": 0.00, "posixio_count": 7569, "USER": "user", "wtime": 0.01, "command": "/bin/hostname" }

to be printed out on STDOUT

**Comment by laurent-nguyen** [comment]
Ok
Can you try to export the following variable?

export SELFIE_LOG=1

(But don't forget to set the time_limit in the configuration file with the correct duration to have the result).

**Comment by laurent-nguyen** [comment]
Hello camilo1729,
did the SELFIE_LOG variable work for you?

**Comment by camilo1729** [comment]
Hello,

Yes, it worked perfectly thank you

**Comment by laurent-nguyen** [comment]
Ok thanks!
