### ISSUE TITLE
memory bandwidth counter

### ISSUE THREAD

**Issue by camilo1729** [cea-hpc/selFIe#3]
Hello,

I would like some information about the performance counter used to measure memory bandwidth:

OFFCORE_RESPONSE_0:ANY_DATA:ANY_RESPONSE

Is there any documentation about it? I was looking for it and I found some different counters to measure memory bandwidth like:

OFFCORE_RESPONSE_0:ANY_DATA_RD:OTHER:ANY_LLC_MISS 
OFFCORE_RESPONSE_0:ANY_DATA:OTHER:ANY_RESPONSE

I have done some experiments and I found that for mono process applications it seems to work but I have found some incoherence in result with MPI applications, for example the benchmark hpl where I got more than the maximum theoretical bandwidth.

I would appreciate any help thank you in advance

**Comment by laurent-nguyen** [comment]
Hello,
I'm sorry, I don't have documentation about it. It's just an assumption. For old processors, you can get a precise bandwidth value by counting the number of cache misses from L3 (or Last Level of Cache). In theory, PAPI provides PAPI_L3_TCM but it doesn't work on our processors. I did explore many counters and as you said OFFCORE_RESPONSE_0:ANY_DATA:ANY_RESPONSE does work for STREAM benchmark for example. But not for parallel codes. Intel explanations said that counter doesn't take all instructions implied in bandwidth calculations.

If you find interesting counters, I'm interested!
